server:
  port: 8467


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-iomuk6uq.sql.tencentcdb.com:23124/springboot_demo
    username: root
    password: Dragonback2022
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
