server:
  max-http-header-size: 32KB
  tomcat:
    max-threads: 512                # 最大线程数
    min-spare-threads: 16           # 最小线程数

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: true

mybatis:
  type-aliases-package: com.dragon.common.base.db.entity
  mapper-locations: classpath:/mapper/*Mapper.xml